[app]
# The name of your app as displayed in the menu
name = "Hexling"

# The submenu where your app should appear.
# One of: "Badge", "Music", "Media", "Apps", "Games", "Background", "Pattern"
category = "Apps"

[entry]
# The name of your entry point `Application` class
# class = "HexlingApp"

[metadata]
# Your nickname.  Must be at most 32 characters!
author = "davesnowdon"

# License of your app as an SPDX identifier: <https://spdx.org/licenses/>
license = "LGPL-3.0-only"

# URL to the repository of your app.
url = "https://github.com/davesnowdon/hexling"

# Description of your app.  Maximum 140 characters!
description = "A robot pet for your Tildagon: feed, stroke and play with it. Moves for real with a BadgeBot/HexDrive hexpansion."

# Version number of your app.  If you push a commit where this number is
# increased, we interpret this as a new version being released.
#
# Version number must be a string!
version = "0.0.1"
